language = []
language.append({"none":""})
language.append({"ABAP":"abap"})
language.append({"ActionScript":"actionscript"})
language.append({"Ada":"ada"})
language.append({"Apache Configuration":"apacheconf"})
language.append({"APL":"apl"})
language.append({"AppleScript":"applescript"})
language.append({"AsciiDoc":"asciidoc"})
language.append({"ASP.NET (C#)":"aspnet"})
language.append({"AutoIt":"autoit"})
language.append({"AutoHotkey":"autohotkey"})
language.append({"Bash":"bash"})
language.append({"BASIC":"basic"})
language.append({"Batch":"batch"})
language.append({"Bison":"bison"})
language.append({"Brainfuck":"brainfuck"})
language.append({"Bro":"bro"})
language.append({"C":"c"})
language.append({"C#":"csharp"})
language.append({"C++":"cpp"})
language.append({"CoffeeScript":"coffeescript"})
language.append({"Crystal":"crystal"})
language.append({"CSS":"css"})
language.append({"CSS Extras":"css-extras"})
language.append({"D":"d"})
language.append({"Dart":"dart"})
language.append({"Diff":"diff"})
language.append({"Docker":"docker"})
language.append({"Eiffel":"eiffel"})
language.append({"Elixir":"elixir"})
language.append({"Erlang":"erlang"})
language.append({"F#":"fsharp"})
language.append({"Fortran":"fortran"})
language.append({"Gherkin":"gherkin"})
language.append({"Git":"git"})
language.append({"GLSL":"glsl"})
language.append({"Go":"go"})
language.append({"GraphQL":"graphql"})
language.append({"Groovy":"groovy"})
language.append({"Haml":"haml"})
language.append({"Handlebars":"handlebars"})
language.append({"Haskell":"haskell"})
language.append({"Haxe":"haxe"})
language.append({"HTTP":"http"})
language.append({"Icon":"icon"})
language.append({"Inform 7":"inform7"})
language.append({"Ini":"ini"})
language.append({"J":"j"})
language.append({"Jade":"jade"})
language.append({"Java":"java"})
language.append({"JavaScript":"javascript"})
language.append({"JSON":"json"})
language.append({"Julia":"julia"})
language.append({"Keyman":"keyman"})
language.append({"Kotlin":"kotlin"})
language.append({"LaTeX":"latex"})
language.append({"Less":"less"})
language.append({"LiveScript":"livescript"})
language.append({"LOLCODE":"lolcode"})
language.append({"Lua":"lua"})
language.append({"Makefile":"makefile"})
language.append({"Markdown":"markdown"})
language.append({"Markup":"markup"})
language.append({"MATLAB":"matlab"})
language.append({"MEL":"mel"})
language.append({"Mizar":"mizar"})
language.append({"Monkey":"monkey"})
language.append({"NASM":"nasm"})
language.append({"nginx":"nginx"})
language.append({"Nim":"nim"})
language.append({"Nix":"nix"})
language.append({"NSIS":"nsis"})
language.append({"Objective-C":"objectivec"})
language.append({"OCaml":"ocaml"})
language.append({"Oz":"oz"})
language.append({"PARI/GP":"parigp"})
language.append({"Parser":"parser"})
language.append({"Pascal":"pascal"})
language.append({"Perl":"perl"})
language.append({"PHP":"php"})
language.append({"PHP Extras":"php-extras"})
language.append({"PowerShell":"powershell"})
language.append({"Processing":"processing"})
language.append({"Prolog":"prolog"})
language.append({".properties":"properties"})
language.append({"Protocol Buffers":"protobuf"})
language.append({"Puppet":"puppet"})
language.append({"Pure":"pure"})
language.append({"Python":"python"})
language.append({"Q":"q"})
language.append({"Qore":"qore"})
language.append({"R":"r"})
language.append({"React JSX":"jsx"})
language.append({"reST (reStructuredText)":"rest"})
language.append({"Rip":"rip"})
language.append({"Roboconf":"roboconf"})
language.append({"Ruby":"ruby"})
language.append({"Rust":"rust"})
language.append({"SAS":"sas"})
language.append({"Sass (Sass)":"sass"})
language.append({"Sass (Scss)":"scss"})
language.append({"Scala":"scala"})
language.append({"Scheme":"scheme"})
language.append({"Smalltalk":"smalltalk"})
language.append({"Smarty":"smarty"})
language.append({"SQL":"sql"})
language.append({"Stylus":"stylus"})
language.append({"Swift":"swift"})
language.append({"Tcl":"tcl"})
language.append({"Textile":"textile"})
language.append({"Twig":"twig"})
language.append({"TypeScript":"typescript"})
language.append({"Verilog":"verilog"})
language.append({"VHDL":"vhdl"})
language.append({"vim":"vim"})
language.append({"Wiki markup":"wiki"})
language.append({"Xojo (REALbasic)":"xojo"})
language.append({"YAML":"yaml"})
